// test-react-app/src/views/MonitorTest.jsx
import { monitor } from '../monitor'

export default function MonitorTest() {
  const testRuntimeError = () => {
    try {
      const undefinedVar = null
      undefinedVar.someMethod()
    } catch (error) {
      monitor.reportError(error, { test: 'runtime-error' })
    }
  }

  const testPromiseError = () => {
    const promise = new Promise((_, reject) => {
      setTimeout(() => reject(new Error('Promise rejection error')), 100)
    })
    promise.catch(error => monitor.reportError(error, { test: 'promise-error' }))
  }

  const testNetworkRequest = () => {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', 'https://jsonplaceholder.typicode.com/todos/1')
    xhr.send()
    fetch('https://jsonplaceholder.typicode.com/posts/1')
      .then(r => r.json())
      .then(data => console.log('Fetch response:', data))
  }

  const testUserBehavior = () => {
    monitor.addBreadcrumb('custom', {
      message: '用户执行了自定义操作',
      data: { test: 'data' }
    })
  }

  const testConsoleOutput = () => {
    console.log('测试 - log')
    console.warn('测试 - warn')
    console.error('测试 - error')
  }

  const testComponentError = () => {
    try {
      throw new Error('Test component render error')
    } catch (error) {
      monitor.reportError(error, { test: 'component-error', componentName: 'ErrorComponent' })
    }
  }

  const testManualErrorReport = () => {
    monitor.reportError(new Error('手动上报的错误'), { context: 'test', customData: 'custom data' })
  }

  return (
    <div className="page-monitor-test">
      <h1>监控测试</h1>
      <p>点击下方按钮测试 SDK 功能，请打开控制台和网络面板查看上报。</p>
      <div className="test-buttons">
        <h3>错误监控</h3>
        <button onClick={testRuntimeError}>运行时错误</button>
        <button onClick={testPromiseError}>Promise 错误</button>
        <button onClick={testComponentError}>组件错误</button>
        <button onClick={testManualErrorReport}>手动上报错误</button>
        <h3>性能与网络</h3>
        <button onClick={testNetworkRequest}>网络请求</button>
        <h3>用户行为</h3>
        <button onClick={testUserBehavior}>行为追踪</button>
        <button onClick={testConsoleOutput}>控制台输出</button>
      </div>
    </div>
  )
}

// test-vue-app/src/views/MonitorTest.vue
<template>
  <div class="page-monitor-test">
    <h1>监控测试</h1>
    <p>点击下方按钮测试 SDK 功能，请打开控制台和网络面板查看上报。</p>
    <div class="test-buttons">
      <h3>错误监控</h3>
      <button @click="triggerError">触发错误（测试上报）</button>
      <button @click="triggerMethodError">触发方法内错误</button>
      <button @click="testManualError">手动上报错误</button>
      <h3>用户行为与网络</h3>
      <button @click="testUserBehavior">行为追踪</button>
      <button @click="testNetworkRequest">网络请求</button>
    </div>
  </div>
</template>

<script>
import { monitor } from '../monitor.js'

export default {
  name: 'MonitorTest',
  methods: {
    triggerError() {
      throw new Error('这是一个测试错误（Vue 组件）')
    },
    triggerMethodError() {
      const a = null
      a.foo()
    },
    testManualError() {
      monitor.reportError(new Error('手动上报的错误'), { context: 'test' })
    },
    testUserBehavior() {
      monitor.addBreadcrumb('custom', { message: '用户执行了自定义操作', data: { test: 'data' } })
    },
    testNetworkRequest() {
      fetch('https://jsonplaceholder.typicode.com/posts/1')
        .then(r => r.json())
        .then(data => console.log('Fetch response:', data))
    }
  }
}
</script>

<style scoped>
.test-buttons { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 0.75rem; margin-top: 1rem; }
.test-buttons h3 { grid-column: 1 / -1; margin: 1rem 0 0.25rem; font-size: 1rem; }
.test-buttons h3:first-child { margin-top: 0; }
.test-buttons button { min-width: 140px; padding: 8px 16px; cursor: pointer; }
</style>
